const fs = require('fs');

const games = [
  {
    id: 1,
    title: 'Cyberpunk 2077',
    description: 'An open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2mld.jpg',
    size: '70 GB',
    downloadUrl: 'https://example.com/cyberpunk',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    releaseDate: '2020',
    rating: '86%',
    genres: 'Action, RPG',
    featured: true
  },
  {
    id: 2,
    title: 'Elden Ring',
    description: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co4jni.jpg',
    size: '60 GB',
    downloadUrl: 'https://example.com/eldenring',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseDate: '2022',
    rating: '96%',
    genres: 'RPG, Action',
    featured: true
  },
  {
    id: 3,
    title: 'Red Dead Redemption 2',
    description: 'America, 1899. The end of the Wild West era has begun. After a robbery goes badly wrong, Arthur Morgan and the Van der Linde gang are forced to flee.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1q1f.jpg',
    size: '150 GB',
    downloadUrl: 'https://example.com/rdr2',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    releaseDate: '2019',
    rating: '97%',
    genres: 'Action, Adventure',
    featured: true
  },
  {
    id: 4,
    title: 'Baldurs Gate 3',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co5s5b.jpg',
    size: '122 GB',
    downloadUrl: 'https://example.com/bg3',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    releaseDate: '2023',
    rating: '96%',
    genres: 'RPG, Strategy',
    featured: true
  },
  {
    id: 5,
    title: 'The Witcher 3: Wild Hunt',
    description: 'As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1wyy.jpg',
    size: '50 GB',
    downloadUrl: 'https://example.com/witcher3',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    releaseDate: '2015',
    rating: '93%',
    genres: 'RPG, Adventure',
    featured: true
  },
  {
    id: 6,
    title: 'GTA V',
    description: 'When a young street hustler, a retired bank robber and a terrifying psychopath land themselves in trouble, they must pull off a series of dangerous heists to survive.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2lbd.jpg',
    size: '95 GB',
    downloadUrl: 'https://example.com/gtav',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    releaseDate: '2013',
    rating: '97%',
    genres: 'Action, Adventure',
    featured: true
  },
  {
    id: 7,
    title: 'Hogwarts Legacy',
    description: 'Experience a new story set at Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co5vmg.jpg',
    size: '85 GB',
    downloadUrl: 'https://example.com/hogwarts',
    developer: 'Avalanche Software',
    publisher: 'Warner Bros',
    releaseDate: '2023',
    rating: '84%',
    genres: 'RPG, Adventure',
    featured: true
  },
  {
    id: 8,
    title: 'Starfield',
    description: 'In this next generation role-playing game set amongst the stars, create any character you want and explore with unparalleled freedom.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co5w0l.jpg',
    size: '125 GB',
    downloadUrl: 'https://example.com/starfield',
    developer: 'Bethesda Game Studios',
    publisher: 'Bethesda Softworks',
    releaseDate: '2023',
    rating: '83%',
    genres: 'RPG, Shooter',
    featured: false
  },
  {
    id: 9,
    title: 'Spider-Man Remastered',
    description: 'In Marvels Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide in an original action-packed story.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co3s77.jpg',
    size: '75 GB',
    downloadUrl: 'https://example.com/spiderman',
    developer: 'Insomniac Games',
    publisher: 'Sony',
    releaseDate: '2022',
    rating: '87%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 10,
    title: 'God of War',
    description: 'His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1tmu.jpg',
    size: '70 GB',
    downloadUrl: 'https://example.com/gow',
    developer: 'Santa Monica Studio',
    publisher: 'Sony',
    releaseDate: '2022',
    rating: '94%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 11,
    title: 'Resident Evil 4 Remake',
    description: 'Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co6kxp.jpg',
    size: '67 GB',
    downloadUrl: 'https://example.com/re4',
    developer: 'Capcom',
    publisher: 'Capcom',
    releaseDate: '2023',
    rating: '93%',
    genres: 'Action, Horror',
    featured: false
  },
  {
    id: 12,
    title: 'Sekiro: Shadows Die Twice',
    description: 'Carve your own clever path to vengeance in the award winning adventure from developer FromSoftware.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1iw8.jpg',
    size: '25 GB',
    downloadUrl: 'https://example.com/sekiro',
    developer: 'FromSoftware',
    publisher: 'Activision',
    releaseDate: '2019',
    rating: '90%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 13,
    title: 'Doom Eternal',
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1z0y.jpg',
    size: '80 GB',
    downloadUrl: 'https://example.com/doom',
    developer: 'id Software',
    publisher: 'Bethesda',
    releaseDate: '2020',
    rating: '88%',
    genres: 'Shooter, Action',
    featured: false
  },
  {
    id: 14,
    title: 'Hades',
    description: 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2i7u.jpg',
    size: '15 GB',
    downloadUrl: 'https://example.com/hades',
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    releaseDate: '2020',
    rating: '93%',
    genres: 'Action, RPG',
    featured: false
  },
  {
    id: 15,
    title: 'Horizon Zero Dawn',
    description: 'Experience Aloys legendary quest to unravel the mysteries of a future Earth ruled by Machines.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co3pho.jpg',
    size: '100 GB',
    downloadUrl: 'https://example.com/horizon',
    developer: 'Guerrilla Games',
    publisher: 'Sony',
    releaseDate: '2020',
    rating: '89%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 16,
    title: 'Assassins Creed Valhalla',
    description: 'Become Eivor, a Viking raider raised to be a fearless warrior, and lead your clan from icy desolation in Norway to a new home amid the lush farmlands of ninth-century England.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2gvu.jpg',
    size: '110 GB',
    downloadUrl: 'https://example.com/acvalhalla',
    developer: 'Ubisoft Montreal',
    publisher: 'Ubisoft',
    releaseDate: '2020',
    rating: '81%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 17,
    title: 'Dark Souls III',
    description: 'As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1vcf.jpg',
    size: '25 GB',
    downloadUrl: 'https://example.com/ds3',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseDate: '2016',
    rating: '89%',
    genres: 'Action, RPG',
    featured: false
  },
  {
    id: 18,
    title: 'Monster Hunter: World',
    description: 'Welcome to a new world! Take on the role of a hunter and slay ferocious monsters in a living, breathing ecosystem.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1u7l.jpg',
    size: '48 GB',
    downloadUrl: 'https://example.com/mhw',
    developer: 'Capcom',
    publisher: 'Capcom',
    releaseDate: '2018',
    rating: '90%',
    genres: 'Action, RPG',
    featured: false
  },
  {
    id: 19,
    title: 'Control',
    description: 'After a secretive agency in New York is invaded by an otherworldly threat, you become the new Director struggling to regain Control.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co1ir9.jpg',
    size: '42 GB',
    downloadUrl: 'https://example.com/control',
    developer: 'Remedy Entertainment',
    publisher: '505 Games',
    releaseDate: '2019',
    rating: '85%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 20,
    title: 'Death Stranding',
    description: 'From legendary game creator Hideo Kojima comes a genre-defying experience, now expanded in this definitive Directors Cut.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2f5l.jpg',
    size: '80 GB',
    downloadUrl: 'https://example.com/deathstranding',
    developer: 'Kojima Productions',
    publisher: '505 Games',
    releaseDate: '2020',
    rating: '82%',
    genres: 'Action, Adventure',
    featured: false
  },
  {
    id: 21,
    title: 'Forza Horizon 5',
    description: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co3oxh.jpg',
    size: '103 GB',
    downloadUrl: 'https://example.com/fh5',
    developer: 'Playground Games',
    publisher: 'Xbox Game Studios',
    releaseDate: '2021',
    rating: '92%',
    genres: 'Racing, Adventure',
    featured: false
  },
  {
    id: 22,
    title: 'Dying Light 2',
    description: 'The virus won and civilization has fallen back to the Dark Ages. The City, one of the last human settlements, is on the brink of collapse.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co4jiq.jpg',
    size: '70 GB',
    downloadUrl: 'https://example.com/dl2',
    developer: 'Techland',
    publisher: 'Techland',
    releaseDate: '2022',
    rating: '76%',
    genres: 'Action, Horror',
    featured: false
  },
  {
    id: 23,
    title: 'Battlefield 2042',
    description: 'Battlefield 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co3s5s.jpg',
    size: '100 GB',
    downloadUrl: 'https://example.com/bf2042',
    developer: 'DICE',
    publisher: 'EA',
    releaseDate: '2021',
    rating: '68%',
    genres: 'Shooter, Action',
    featured: false
  },
  {
    id: 24,
    title: 'Far Cry 6',
    description: 'Welcome to Yara, a tropical paradise frozen in time. As dictator of Yara, Antón Castillo is intent on restoring his nation back to its former glory.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co3p12.jpg',
    size: '60 GB',
    downloadUrl: 'https://example.com/fc6',
    developer: 'Ubisoft Toronto',
    publisher: 'Ubisoft',
    releaseDate: '2021',
    rating: '73%',
    genres: 'Shooter, Action',
    featured: false
  },
  {
    id: 25,
    title: 'Hitman 3',
    description: 'Death Awaits. Agent 47 returns as a ruthless professional in HITMAN 3 for the most important contracts of his entire career.',
    cover: 'https://images.igdb.com/igdb/image/upload/t_1080p/co2iuf.jpg',
    size: '60 GB',
    downloadUrl: 'https://example.com/hitman3',
    developer: 'IO Interactive',
    publisher: 'IO Interactive',
    releaseDate: '2021',
    rating: '87%',
    genres: 'Action, Stealth',
    featured: false
  }
];

fs.writeFileSync('games.json', JSON.stringify(games, null, 2));
console.log('✅ Seeded', games.length, 'games');
